# Generated by Django 5.0.3 on 2024-03-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0002_remove_apartment_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='num_bathrooms',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bedrooms',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size_sqft',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
