# Generated by Django 5.0.3 on 2024-03-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0003_alter_apartment_num_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='size_sqft',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
