# Generated by Django 5.0.3 on 2024-03-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0009_remove_apartment_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
