# Generated by Django 5.0.3 on 2024-03-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0020_alter_parking_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rate_per_sqft',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='region',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
