# Generated by Django 5.0.3 on 2024-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0024_apartment_predicted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='predicted_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
