# Generated by Django 5.0.3 on 2024-04-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0028_amenities_amenities_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformedAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parking', models.IntegerField(default=0)),
                ('pet_friendly', models.IntegerField(default=0)),
                ('furnished', models.IntegerField(default=0)),
                ('air_conditioning', models.IntegerField(default=0)),
                ('smoking_permitted', models.IntegerField(default=0)),
                ('barrier_free_entrances_ramps', models.IntegerField(default=0)),
                ('visual_aids', models.IntegerField(default=0)),
                ('accessible_washrooms_in_suite', models.IntegerField(default=0)),
                ('heat', models.IntegerField(default=0)),
                ('hydro', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('cable_tv', models.IntegerField(default=0)),
                ('internet', models.IntegerField(default=0)),
                ('laundry_unit', models.IntegerField(default=0)),
                ('laundry_building', models.IntegerField(default=0)),
                ('dishwasher', models.IntegerField(default=0)),
                ('fridge_freezer', models.IntegerField(default=0)),
                ('yard', models.IntegerField(default=0)),
                ('balcony', models.IntegerField(default=0)),
                ('building_security', models.IntegerField(default=0)),
                ('building_elevator', models.IntegerField(default=0)),
                ('building_gym', models.IntegerField(default=0)),
                ('bycycle_parking', models.IntegerField(default=0)),
                ('storage_space', models.IntegerField(default=0)),
                ('amenities_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'transformed_amenities',
            },
        ),
    ]
