# Generated by Django 5.0.3 on 2024-03-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='location',
        ),
        migrations.RemoveField(
            model_name='predictionresults',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='predictionresults',
            name='location',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='predictionresults',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='predictionresults',
            name='apartment',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='lease_term',
            new_name='agreement_type',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='monthly_rent',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='property_name',
            new_name='rental_type',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='number_of_units',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.DeleteModel(
            name='PredictionResults',
        ),
    ]
