# Generated by Django 5.0.3 on 2024-03-25 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0005_location_apartment_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='llm_core.location'),
        ),
    ]
