# Generated by Django 5.0.3 on 2024-03-25 00:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0006_apartment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parking', models.FloatField(default=False)),
                ('pet_friendly', models.CharField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('smoking_permitted', models.CharField(default=False)),
                ('elevator_accessibility_features', models.BooleanField(default=False)),
                ('barrier_free_entrances_ramps', models.CharField(default=False)),
                ('visual_aids', models.CharField(default=False)),
                ('accessible_washrooms_in_suite', models.CharField(default=False)),
                ('heat', models.BooleanField(default=False)),
                ('hydro', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('cable_tv', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('laundry_unit', models.BooleanField(default=False)),
                ('laundry_building', models.BooleanField(default=False)),
                ('dishwasher', models.BooleanField(default=False)),
                ('fridge_freezer', models.BooleanField(default=False)),
                ('yard', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('building_security', models.BooleanField(default=False)),
                ('building_elevator', models.BooleanField(default=False)),
                ('building_gym', models.BooleanField(default=False)),
                ('bycycle_parking', models.BooleanField(default=False)),
                ('storage_space', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='move_in_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='amenities',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='llm_core.amenities'),
        ),
    ]
