# Generated by Django 5.0.3 on 2024-03-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0007_amenities_apartment_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='elevator_accessibility_features',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='available_date',
        ),
    ]
