# Generated by Django 5.0.3 on 2024-03-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0008_remove_amenities_elevator_accessibility_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
    ]
