# Generated by Django 5.0.3 on 2024-03-25 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0011_remove_apartment_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='amenities',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='llm_core.amenities'),
        ),
    ]
