# Generated by Django 5.0.3 on 2024-03-25 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0015_alter_apartment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.ForeignKey(default='Halifax', on_delete=django.db.models.deletion.CASCADE, to='llm_core.location'),
        ),
    ]
