# Generated by Django 5.0.3 on 2024-03-25 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0017_alter_apartment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('available', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('tenant_services_coordinator', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('resident_managers', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('commercial_property_manager', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fax', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('term', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('termination_policy', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('deposit', models.FloatField(blank=True, default=0, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_core.location')),
            ],
        ),
    ]
