# Generated by Django 5.0.3 on 2024-03-25 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0019_alter_parking_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='available',
            field=models.CharField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
