# Generated by Django 5.0.3 on 2024-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0021_apartment_lat_apartment_long_apartment_rate_per_sqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='postal_code',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
