# Generated by Django 5.0.3 on 2024-03-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0023_alter_apartment_lat_alter_apartment_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
