# Generated by Django 5.0.3 on 2024-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0025_alter_apartment_predicted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('civic_address', models.CharField(max_length=200)),
                ('floors', models.IntegerField()),
                ('units', models.IntegerField()),
                ('developer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Under Development', 'Under Development'), ('Completed', 'Completed')], max_length=20)),
                ('website', models.URLField()),
                ('property_type', models.CharField(choices=[('Condo', 'Condo'), ('Rental', 'Rental')], max_length=10)),
                ('completion_estimate', models.CharField(blank=True, max_length=50)),
                ('retail_sq_ft', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=250)),
            ],
        ),
    ]
