# Generated by Django 5.0.3 on 2024-04-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0026_construction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amenities',
            table='amenities',
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='apartment',
        ),
        migrations.AlterModelTable(
            name='construction',
            table='construction',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='parking',
            table='parking',
        ),
    ]
