# Generated by Django 5.0.3 on 2024-04-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0027_alter_amenities_table_alter_apartment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='amenities_count',
            field=models.IntegerField(default=0),
        ),
    ]
